version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: gigalixir-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gigalixir_getting_started_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
